CREATE TABLE IF NOT EXISTS client (
	id                      TEXT PRIMARY KEY,  -- UUID generated by client
	created_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	host_name               TEXT NOT NULL UNIQUE,
	min_poll_interval_in_ms INTEGER NOT NULL DEFAULT 3000
);

CREATE TABLE IF NOT EXISTS client_watch_group (
	id              INTEGER PRIMARY KEY,
	created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	client_id       TEXT NOT NULL REFERENCES client(id) ON DELETE CASCADE,
	path_to_monitor TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS client_watch_group_excluded_dir (
	id			INTEGER PRIMARY KEY,
	client_watch_group	INTEGER NOT NULL REFERENCES client_watch_group(id) ON DELETE CASCADE,
	exclude_dir		TEXT NOT NULL
);

-- Auto-update updated_at on row modification
CREATE TRIGGER client_updated_at
AFTER UPDATE ON client
FOR EACH ROW
BEGIN
	UPDATE client SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;

CREATE TRIGGER client_watch_group_updated_at
AFTER UPDATE ON client_watch_group
FOR EACH ROW
BEGIN
	UPDATE client_watch_group SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
